### ISSUE TITLE
Support for multiple versions of erlang

### ISSUE THREAD

**Issue by tomciopp** [bitwalker/alpine-erlang#105]
@bitwalker As of right now the project only supports the most recent versions of both elixir and alpine linux. Due to the addition of the JIT a lot of libraries in elixir and erlang are not yet compatible with OTP 24. By adding support for multiple versions of erlang we can continue to ensure that people who rely on the most recent long term stable versions while allowing them to stay up to date with the underlying operating system.

Since we've updated to buildx, we should be able to modify the `Makefile` so that we can build multiple versions of the Dockerfile based on everyone's needs. Let me know what you think.

**Comment by bitwalker** [comment]
This should be as simple as setting up a build matrix in the GitHub Actions workflow, and setting `VERSION` in the environment to whatever version we wish to build. As far as I'm aware there are no major differences in the build flags between OTP 23.x and 24+, so that should be sufficient to build and release multiple versions.

We probably need to tweak the Makefile though to _not_ build the `:latest` tag for every build, but only for whichever version is actually the latest. That should be able to be accomplished as part of the build matrix, but I don't recall off the top of my head what the best way to go is there.

Anyway, I'm generally in favor, so if a PR along these lines is opened, I'm happy to sign off.

**Comment by bitwalker** [comment]
This was merged in #106
