### ISSUE TITLE
openssl-1.1.1d-r3 on alpine 3.11.5 contains CVE-2020-1967

### ISSUE THREAD

**Issue by tonnyadhi** [bitwalker/alpine-erlang#76]
Dear bitwalker,
alpine 3.11.5 that used as based for your alpine-erlang image contains CVE-2020-1967. It is categorize as a high risk CVE. In my pipeline , i used trivy as docker cve scanner. Of course the build will halt when trivy scanned your image. Could you update the openssl package, because alpine is not updated their package yet. Or we just wait for another build.

**Comment by bitwalker** [comment]
As soon as OpenSSL is updated in the Alpine repos, I'm happy to rebuild the image. The ones I provide on Docker Hub are for convenience though, I don't use them directly (for that I build the images in my own repo). 

If it is a high priority to fix it and you can't wait, then I'd recommend taking the Dockerfile in this repo, adding a custom OpenSSL build to it, and build it manually, rather than using the images on Docker Hub.

**Comment by bitwalker** [comment]
Alpine has been updated in the image, so this should no longer be an issue. Thanks again for reporting!
